### ISSUE TITLE
Print- Failure to print.

### ISSUE THREAD

**Issue by ollielau** [county-of-simcoe-gis/SimcoeCountyWebViewer#14]
@Saspect-IO

Conditions: Export to 11x8 JPG, symbolized circle, old 1997 aerial imagery.
![image](https://user-images.githubusercontent.com/56846925/67521800-93a43a00-f679-11e9-8503-1832997395b7.png)

**Comment by Saspect-IO** [comment]
@iquitwow  @ollielau  
**Jrxml Constraints**
1. jrxml does not support jpg format. All templates except **Map Only** will fail to print with JPG.
2. Being that the **Map Only** template is not at scale it is set to bypass the jrxml template thus accepting JPG format.
