### ISSUE TITLE
rc/1.1.x - Cannot read property 'forEach' of undefined at mergeObjArray (helpers.js)  

### ISSUE THREAD

**Issue by oren-ned** [county-of-simcoe-gis/SimcoeCountyWebViewer#160]
Possible issue with the object in the DB config file.

![Capture](https://user-images.githubusercontent.com/10034654/137943345-f10956b6-b752-41c4-81b0-0ead2213e345.PNG)

**Comment by reed-tom** [comment]
I've removed the offending code, it should load properly now.
