### ISSUE TITLE
(branch rc/1.2.x) Table of Content: List View and Group View are not synchronized for layers created by Add Data

### ISSUE THREAD

**Issue by sjyangkevin** [county-of-simcoe-gis/SimcoeCountyWebViewer#163]
Hi

I noticed that there is an issue with the List view and Group View after adding data by using the Add Data tool. 

Suppose I am currently under Group View, and I open up the Add Data tool and then upload an KML file. A layer will be created and will be added to the group that is specified in the Add Data tool. After that, if I switched to List View, the layer that I just added disappear, and I cannot find it in either All Layers or the group that I added this layer. As the following screenshots show (first two images are in Group View, and the last two are in List View):

![image](https://user-images.githubusercontent.com/85313829/138351046-5b2f9d7a-b6e5-40e6-880f-bb6d95160843.png)
![image](https://user-images.githubusercontent.com/85313829/138351105-2a73cec8-9c3e-4de6-9dc4-2ce6daf8f53f.png)
![image](https://user-images.githubusercontent.com/85313829/138351186-a07f3fb5-25ad-468b-b4d1-0708cb529e8b.png)
![image](https://user-images.githubusercontent.com/85313829/138351234-f036ec72-170b-40bf-a499-8b5ae288b130.png)

When I switched back to the Group View, the added layer is still in there. The same situation happens when I added a layer in the situation that I am under List View, and the layer is not showing up in Group View. I am thinking that the state of layer changes is not synchronized for these two views

Thanks,

**Comment by reed-tom** [comment]
This was done intentionally, the table of contents views are not meant to be synchronized.   The idea was that users could flip between views and they would remain unchanged so that they could potentially be used for different tasks.
