### ISSUE TITLE
(branch rc/1.2.x) Layers added from the "Services" in Add Data tool failed to be identified

### ISSUE THREAD

**Issue by sjyangkevin** [county-of-simcoe-gis/SimcoeCountyWebViewer#164]
Hi,

When I tried to identified a feature from the layers added through the "Services" tab in Add Data tool, and the application throws the error in the below screenshot when I tried to identify it. It was identifiable before.    

![image](https://user-images.githubusercontent.com/85313829/138353419-ae530e11-d397-49cb-9297-b8e007ede865.png)
![image](https://user-images.githubusercontent.com/85313829/138353081-d9edbbf1-e1f4-4fab-b408-464775a93192.png)

By opening the URL, I can actually see the data obtained from the server, like below:   

![image](https://user-images.githubusercontent.com/85313829/138353521-8b7444c2-db13-44ba-ae9d-c476c4f0966c.png)

Thanks,

**Comment by reed-tom** [comment]
CORS prevents identify from localhost.  Identify does work on some of the service layers, but it's very dependant on the added layers
