### ISSUE TITLE
"Add to My Maps" not works after identifying a feature from layers added from Services

### ISSUE THREAD

**Issue by sjyangkevin** [county-of-simcoe-gis/SimcoeCountyWebViewer#165]
Hi,

When I open up the application with [the link provided on the homepage](https://opengis.simcoe.ca/public), I added a layer from the "Services" by using the Add Data tool. The "Add to My Maps" button in the Reports tab is not working after I identifying a feature from that layer, and the app throws the following error. (It was an issue in the rc/1.2.x branch before, but since now the identify is not working for those layers added via Services in rc/1.2.x, I use the link provided on the home page to open the application, and also found this issues)  

`Uncaught TypeError: Cannot read property 'getType' of null`

![image](https://user-images.githubusercontent.com/85313829/138354233-ae976cd7-9178-4a81-aead-b7c29fbbe00d.png)

Thanks,

**Comment by sjyangkevin** [comment]
The layers fetched from Services or URLs are ImageWMS, and the geometry is null, and [line 376](https://github.com/county-of-simcoe-gis/SimcoeCountyWebViewer/blob/6326f79e44480d1fe12a55a364271910aea8bbe0/src/sidebar/components/mymaps/MyMaps.jsx#L376) trying to get the type of the feature's geometry, resulting in this error.

feature.getGeometry().getType()

**Comment by reed-tom** [comment]
added additional check for unavailable geometry when adding geometry from the emitter
