### ISSUE TITLE
Right mouse click behavior - while using Draw and Measurement tools

### ISSUE THREAD

**Issue by oren-ned** [county-of-simcoe-gis/SimcoeCountyWebViewer#166]
Right moues click is still working while **Draw** and **Measurement** tools are in use.  Right mouse button opens content menu and also works as left click. 

Suggestion: Left click can be configured to cancel the current Drawing Tool action and the RED x can button can be removed from Draw tool bar. 

![IssueReport1](https://user-images.githubusercontent.com/10034654/138530785-e9b41d2c-d478-47c1-9a36-ee3062e83564.PNG)

**Comment by reed-tom** [comment]
added check for drawing or measuring when right click is pressed on 
https://github.com/county-of-simcoe-gis/SimcoeCountyWebViewer/tree/bug/add-layer-identify-issues
