### ISSUE TITLE
Disclaimer pop-up is not respected when all group is turned on in the TOC (Group - Turn On All)

### ISSUE THREAD

**Issue by oren-ned** [county-of-simcoe-gis/SimcoeCountyWebViewer#170]
When a TOC group which includes a layer with Disclaimer pop-up (such as Terrane parcel) is turned on all layer included in that group turn on without showing a pop-up for the restricted layer.

**Comment by reed-tom** [comment]
fixed in branch https://github.com/county-of-simcoe-gis/SimcoeCountyWebViewer/tree/bug/add-layer-identify-issues
