### ISSUE TITLE
Polygons added to My Maps (by identify) doesn't allow change of fill colour

### ISSUE THREAD

**Issue by oren-ned** [county-of-simcoe-gis/SimcoeCountyWebViewer#177]
This is affecting only rc1.2.x - Polygons added to my maps by identifying a polygons data layer doesn't allow user to change the fill-color or fill-transparency.  

![image](https://user-images.githubusercontent.com/10034654/150144176-a9b71cbe-47dd-4785-bddc-d41dca91c517.png)

**Comment by reed-tom** [comment]
fixed in https://github.com/county-of-simcoe-gis/SimcoeCountyWebViewer/tree/hotfix/allow-fill-multipolygon
