### ISSUE TITLE
View in Google Map (right mouse click context menu) - Refused to Connect. 

### ISSUE THREAD

**Issue by oren-ned** [county-of-simcoe-gis/SimcoeCountyWebViewer#178]
rc/2.1.x - When the Google map is triggered from the right mouse click context menu internal browser pops-up refuses to connect.
 
![image](https://user-images.githubusercontent.com/10034654/150145486-f1bdfc69-dd07-48f1-a3a3-183042e24f5f.png)

**Comment by reed-tom** [comment]
fixed in https://github.com/county-of-simcoe-gis/SimcoeCountyWebViewer/tree/bug/add-layer-identify-issues
