### ISSUE TITLE
Theme or Tool Enabled - More... option does not slide out the side panel when colapsed

### ISSUE THREAD

**Issue by ghudolin** [county-of-simcoe-gis/SimcoeCountyWebViewer#2]
If a user has enabled a tool or theme and then collapsed the side panel and then attempts to use the link to that item under the "More...' button in the bottom left the panel does not slide back out and return them to their selection.

**Comment by iquitwow** [comment]
I'm guessing the MTO merge from last week referenced this issue.   I did not fix it.

**Comment by iquitwow** [comment]
Fixed. 5fb4a93a6e78688f96f2230d82db22439f3547d0
