### ISSUE TITLE
Increasing Outline Width to Maximum Makes Feature Disappear

### ISSUE THREAD

**Issue by ollielau** [county-of-simcoe-gis/SimcoeCountyWebViewer#21]
![image](https://user-images.githubusercontent.com/56846925/68315108-4a92b380-0085-11ea-8f13-f07a99d8df5f.png)
@Saspect-IO

Increasing the Width bar to maximum under the outline removed the drawing temporarily from sight.

**Comment by Saspect-IO** [comment]
@iquitwow  @ollielau 
Does this occur in the UI on screen or is drawing missing on the print out document?
Also I have not been able to replicate the error thus far.

**Comment by ollielau** [comment]
@Saspect-IO 

After some further testing, this seems to only happen in the UI, and only with the Point drawings. Increasing the size of a Circle drawing, for instance, does not disappear from the UI.

**Comment by ollielau** [comment]
This seems to have been resolved.
