### ISSUE TITLE
Typing - or + into the search box is zooming in or out.

### ISSUE THREAD

**Issue by oren-ned** [county-of-simcoe-gis/SimcoeCountyWebViewer#29]

**Comment by iquitwow** [comment]
Grant, I can prevent the Map keyboard events if the search box has focus.  Are you ok with that?
The major issue I see is we'll likely have the search box focused by default for Tab ordering.  What do you think?

**Comment by oren-ned** [comment]
Some more observations: When you start  typing in the search box and item list appears (in the drop- down) a common behavior would be user to use up-down arrow keys to pick the item they are looking for instead of typing it all or using mouse to pick the item form drop down list.  Currently up-down  arrows works for both search box and map screen at the same time.   Map can have focus by default and the Search box can be the second (get the focus after first tab press).

**Comment by iquitwow** [comment]
https://github.com/county-of-simcoe-gis/SimcoeCountyWebViewer/commit/b678f6de67e02736ec0797117f39d21fac04a2c5

On startup, Map has focus (FYI it already had focus) , next tab is search box then burger button (enter to execute button).  Rest of tab order to be determined but for now it goes to Layers tab and then each layer.

When Search Box has focus the map keyboard events are disabled.

@ghudolin let me know if you're ok with this and I'll close this issue.

**Comment by oren-ned** [comment]
Great!   It works as expected!
