### ISSUE TITLE
ADD-LAYER FUNCTION

### ISSUE THREAD

**Issue by oren-ned** [county-of-simcoe-gis/SimcoeCountyWebViewer#33]
**Adding layers to “Pre-Defined Maps (Groups)” from the "All layers" Group**

If “Historical”, “Popular” and “Topo Overly” are pre-defined maps then allowing end-user to add layers from “All Layers" group (which is the list of all the available layers) to the pre-defined maps. 

This change will allow more flexibility MAP configuration pattern for pre-defined maps while allowing "All Layers" group layers is parsed and created in the background since it will be used a list of all available layers which can be added to the per-configured maps.  All Layers may not be needed as a pre-configured map???.

Add layer function can use the “Search Function” which will show only “All Layers” group content and when user clicks to the plus (+) beside the search dorp down this layer will be added to the active Map Configuration (Group). 

Additionally an "Add Layer” button can be placed somewhere on the TOC which will get focus to Search drop down and extend it with layers listed when pressed.

**Comment by reed-tom** [comment]
Add layer tool can now add to either list or folder style TOC
