### ISSUE TITLE
add a guide on how to set up a working local version for development including the api and geoserver

### ISSUE THREAD

**Issue by leohoy** [county-of-simcoe-gis/SimcoeCountyWebViewer#34]
I am currently trying to set up the project locally and I am having a hard time configuring all the ports correctly. It would be really a great time saver I think if there would be a guide on how to stitch the together the components Viewer, API and Geoserver.

**Comment by iquitwow** [comment]
I created a guide today.  It's nothing fancy but it's a start.  Please provide feedback if I fell short somewhere.  The guide is here:  https://github.com/county-of-simcoe-gis/SimcoeCountyDeploymentGuide
