### ISSUE TITLE
TOC Stuck at the bottom of the list when a layer activated from Search Bar.

### ISSUE THREAD

**Issue by oren-ned** [county-of-simcoe-gis/SimcoeCountyWebViewer#35]
Steps to re-create the issue.
1-	Load the map (https://opengis.simcoe.ca). 
2-	Search for School.
3-	Click to the School (Popular  Layers) – or you can search and click any other layer in a list other than All Layers.
4-	Back to Search bar and search School again.
5-	This time pick the School (All Layers).
6-	Issue: -- TOC Scrolls to the bottom of the All Layers list and for 8-9 second doesn’t let you scroll up using scroll bar or Mouse.

**Comment by iquitwow** [comment]
Good work finding that.  Works as expected now.  commit 63e6ab72d3669e4d93792ebe9694df4226abbbb2
