### ISSUE TITLE
Would it be possible to deploy the webviewer for custom geoservers

### ISSUE THREAD

**Issue by gigincg** [county-of-simcoe-gis/SimcoeCountyWebViewer#50]
I understand that my requirement is outside the purview of this project, but I need set up a webviewer and a GeoServer in a very short time period and I'm looking for plug and play options. Would it be possible to setup this project with a different Geoserver instance in order to display the layers in said server. Any help would be greatly appreciated. Even any suggestions on other open source plug and play options for a WebGIS. Thank You.

**Comment by iquitwow** [comment]
Not sure if you saw the deployment doc but it might help you understand what is involved to get it setup in your environment:  https://github.com/county-of-simcoe-gis/SimcoeCountyDeploymentGuide

Colleague of mine pointed out this project to me.  https://github.com/vojvod/ocmv
I never got it going so I can't vouch for it personally,  but its bare bones and might work for you.

The other paid option is to use ArcGIS online and point them to your GeoServer WMS layers.
